# Generated by Django 4.0.6 on 2022-07-29 17:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_post',
            field=models.ImageField(null=True, upload_to='post_imagenes/'),
        ),
    ]
