# Generated by Django 4.0.6 on 2022-08-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre_contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo_post',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo_post',
            field=models.CharField(max_length=100),
        ),
    ]
