# Generated by Django 4.0.6 on 2022-07-30 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0003_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
