# Generated by Django 4.0.6 on 2022-08-04 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0005_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_post',
            field=models.ImageField(default='post_imagenes/default.png', null=True, upload_to='post_imagenes/'),
        ),
    ]
