# Generated by Django 4.0.6 on 2022-07-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0006_delete_categoria_delete_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estatus_post',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
